### ISSUE TITLE
Error when registering passkey on Android

### ISSUE THREAD

**Issue by briancorbin** [corbado/flutter-passkeys#58] opened 2024-03-25 23:58 UTC
I'm running in to an error when registering a passkey only on Android, iOS works just fine. Any idea what is causing this?

`PlatformException(android-unhandledGoogle Password Manager, UNKNOWN EXCEPTION - java.lang.IllegalArgumentException: bad base-64, UNKNOWN EXCEPTION - java.lang.IllegalArgumentException: bad base-64, null)`

For reference, here is the code I am running, and it is failing at the `final registerRequestResponse =
    await passkeyAuthenticator.register(registerRequest);` line during registration.

I have confirmed my google account and google play are set up correctly, as I am able to get the initial prompt to register the passkey, but upon clicking "Continue" it fails and errors out.
<img width="435" alt="Screenshot 2024-03-25 at 4 58 12 PM" src="https://github.com/corbado/flutter-passkeys/assets/4346395/bda71530-5ca7-4a9e-b760-ca5dc4263c97">

```typescript
final userHandle = CryptoRNG().generate();
final userHandleEncoded = base64Encode(userHandle);
final passkeyAuthenticator = PasskeyAuthenticator();
final supportsPasskeys = await passkeyAuthenticator.canAuthenticate();
print(supportsPasskeys);
final registerRequest = RegisterRequestType(
  challenge: base64.encode(CryptoRNG().generate()),
  relyingParty: RelyingPartyType(
      name: 'Capsule', id: relyingPartyId ?? environment.relyingPartyId()),
  user: UserType(displayName: email, name: email, id: userHandleEncoded),
  authSelectionType: AuthenticatorSelectionType(
      authenticatorAttachment: 'platform',
      requireResidentKey: true,
      residentKey: 'required',
      userVerification: 'required'),
  pubKeyCredParams: [
    PubKeyCredParamType(
        type: PublicKeyCredentialType.publicKey.value, alg: es256Algorithm),
    PubKeyCredParamType(
        type: PublicKeyCredentialType.publicKey.value, alg: rs256Algorithm),
  ],
  timeout: 60000,
  attestation: 'direct',
  excludeCredentials: [],
);

final registerRequestResponse =
    await passkeyAuthenticator.register(registerRequest);
```

**Comment by vincentdelitz** [comment] 2024-03-26 08:37
Hi @briancorbin,

Which relying party server are you using? A self-hosted one or the Corbado-provided one? If self-hosted, which library are you using?

**Comment by briancorbin** [comment] 2024-03-26 15:23
I have a custom self hosted RPS, no library being used

**Comment by briancorbin** [comment] 2024-03-29 16:55
Hey there, just wondering if you've got any ideas on this?

**Comment by vincentdelitz** [comment] 2024-04-01 09:10
Hey @briancorbin,

From going through your error message again, it said "bad base-64". In your relying party server, can you double-check if you use the right encoding (base64 vs. base64URL). This difference in encoding was for many other developers often a cause for issues.

**Comment by incorbador** [comment] 2024-04-03 09:20
Hey @briancorbin, sorry for the delayed response. @vincentdelitz is exactly right. The issue is caused by the encoding of userHandle. In the code example above it is base64 encoded, but it needs to be base64url encoded. You can test that by replacing base64Encode with base64UrlEncode, then your example runs through and you can create a passkey. 
Does that answer your question? :)

**Comment by briancorbin** [comment] 2024-04-11 21:54
Ah, turns out it was the challenge that needed to be base64url encoded! The userHandle is fine with any string it seems. Thank you for the help!

**Comment by incorbador** [comment] 2024-04-13 13:51
I'll close this issue now, just re-open it or create a new issue if something else in unclear.

**Closed by incorbador** 2024-04-13 13:51 UTC
